<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TigerBetListSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                "bet_size" => 1000,
                "bet_multiple" => 1,
                "basic_bet" => 5,
                "total_bet" => 5000,
                "id" => 1,
                "bet_size_s" => "0.10",
                "total_bet_s" => "0.50",
            ],
            [
                "bet_size" => 1000,
                "bet_multiple" => 2,
                "basic_bet" => 5,
                "total_bet" => 10000,
                "id" => 2,
                "bet_size_s" => "0.10",
                "total_bet_s" => "1.00",
            ],
            [
                "bet_size" => 1000,
                "bet_multiple" => 3,
                "basic_bet" => 5,
                "total_bet" => 15000,
                "id" => 3,
                "bet_size_s" => "0.10",
                "total_bet_s" => "1.50",
            ],
            [
                "bet_size" => 1000,
                "bet_multiple" => 4,
                "basic_bet" => 5,
                "total_bet" => 20000,
                "id" => 4,
                "bet_size_s" => "0.10",
                "total_bet_s" => "2.00",
            ],
            [
                "bet_size" => 1000,
                "bet_multiple" => 5,
                "basic_bet" => 5,
                "total_bet" => 25000,
                "id" => 5,
                "bet_size_s" => "0.10",
                "total_bet_s" => "2.50",
            ],
            [
                "bet_size" => 1000,
                "bet_multiple" => 6,
                "basic_bet" => 5,
                "total_bet" => 30000,
                "id" => 6,
                "bet_size_s" => "0.10",
                "total_bet_s" => "3.00",
            ],
            [
                "bet_size" => 1000,
                "bet_multiple" => 7,
                "basic_bet" => 5,
                "total_bet" => 35000,
                "id" => 7,
                "bet_size_s" => "0.10",
                "total_bet_s" => "3.50",
            ],
            [
                "bet_size" => 1000,
                "bet_multiple" => 8,
                "basic_bet" => 5,
                "total_bet" => 40000,
                "id" => 8,
                "bet_size_s" => "0.10",
                "total_bet_s" => "4.00",
            ],
            [
                "bet_size" => 1000,
                "bet_multiple" => 9,
                "basic_bet" => 5,
                "total_bet" => 45000,
                "id" => 9,
                "bet_size_s" => "0.10",
                "total_bet_s" => "4.50",
            ],
            [
                "bet_size" => 1000,
                "bet_multiple" => 10,
                "basic_bet" => 5,
                "total_bet" => 50000,
                "id" => 10,
                "bet_size_s" => "0.10",
                "total_bet_s" => "5.00",
            ],
            [
                "bet_size" => 10000,
                "bet_multiple" => 1,
                "basic_bet" => 5,
                "total_bet" => 50000,
                "id" => 11,
                "bet_size_s" => "1.00",
                "total_bet_s" => "5.00",
            ],
            [
                "bet_size" => 10000,
                "bet_multiple" => 2,
                "basic_bet" => 5,
                "total_bet" => 100000,
                "id" => 12,
                "bet_size_s" => "1.00",
                "total_bet_s" => "10.00",
            ],
            [
                "bet_size" => 10000,
                "bet_multiple" => 3,
                "basic_bet" => 5,
                "total_bet" => 150000,
                "id" => 13,
                "bet_size_s" => "1.00",
                "total_bet_s" => "15.00",
            ],
            [
                "bet_size" => 10000,
                "bet_multiple" => 4,
                "basic_bet" => 5,
                "total_bet" => 200000,
                "id" => 14,
                "bet_size_s" => "1.00",
                "total_bet_s" => "20.00",
            ],
            [
                "bet_size" => 10000,
                "bet_multiple" => 5,
                "basic_bet" => 5,
                "total_bet" => 250000,
                "id" => 15,
                "bet_size_s" => "1.00",
                "total_bet_s" => "25.00",
            ],
            [
                "bet_size" => 10000,
                "bet_multiple" => 6,
                "basic_bet" => 5,
                "total_bet" => 300000,
                "id" => 16,
                "bet_size_s" => "1.00",
                "total_bet_s" => "30.00",
            ],
            [
                "bet_size" => 10000,
                "bet_multiple" => 7,
                "basic_bet" => 5,
                "total_bet" => 350000,
                "id" => 17,
                "bet_size_s" => "1.00",
                "total_bet_s" => "35.00",
            ],
            [
                "bet_size" => 10000,
                "bet_multiple" => 8,
                "basic_bet" => 5,
                "total_bet" => 400000,
                "id" => 18,
                "bet_size_s" => "1.00",
                "total_bet_s" => "40.00",
            ],
            [
                "bet_size" => 10000,
                "bet_multiple" => 9,
                "basic_bet" => 5,
                "total_bet" => 450000,
                "id" => 19,
                "bet_size_s" => "1.00",
                "total_bet_s" => "45.00",
            ],
            [
                "bet_size" => 10000,
                "bet_multiple" => 10,
                "basic_bet" => 5,
                "total_bet" => 500000,
                "id" => 20,
                "bet_size_s" => "1.00",
                "total_bet_s" => "50.00",
            ],
            [
                "bet_size" => 50000,
                "bet_multiple" => 1,
                "basic_bet" => 5,
                "total_bet" => 250000,
                "id" => 21,
                "bet_size_s" => "5.00",
                "total_bet_s" => "25.00",
            ],
            [
                "bet_size" => 50000,
                "bet_multiple" => 2,
                "basic_bet" => 5,
                "total_bet" => 500000,
                "id" => 22,
                "bet_size_s" => "5.00",
                "total_bet_s" => "50.00",
            ],
            [
                "bet_size" => 50000,
                "bet_multiple" => 3,
                "basic_bet" => 5,
                "total_bet" => 750000,
                "id" => 23,
                "bet_size_s" => "5.00",
                "total_bet_s" => "75.00",
            ],
            [
                "bet_size" => 50000,
                "bet_multiple" => 4,
                "basic_bet" => 5,
                "total_bet" => 1000000,
                "id" => 24,
                "bet_size_s" => "5.00",
                "total_bet_s" => "100.00",
            ],
            [
                "bet_size" => 50000,
                "bet_multiple" => 5,
                "basic_bet" => 5,
                "total_bet" => 1250000,
                "id" => 25,
                "bet_size_s" => "5.00",
                "total_bet_s" => "125.00",
            ],
            [
                "bet_size" => 50000,
                "bet_multiple" => 6,
                "basic_bet" => 5,
                "total_bet" => 1500000,
                "id" => 26,
                "bet_size_s" => "5.00",
                "total_bet_s" => "150.00",
            ],
            [
                "bet_size" => 50000,
                "bet_multiple" => 7,
                "basic_bet" => 5,
                "total_bet" => 1750000,
                "id" => 27,
                "bet_size_s" => "5.00",
                "total_bet_s" => "175.00",
            ],
            [
                "bet_size" => 50000,
                "bet_multiple" => 8,
                "basic_bet" => 5,
                "total_bet" => 2000000,
                "id" => 28,
                "bet_size_s" => "5.00",
                "total_bet_s" => "200.00",
            ],
            [
                "bet_size" => 50000,
                "bet_multiple" => 9,
                "basic_bet" => 5,
                "total_bet" => 2250000,
                "id" => 29,
                "bet_size_s" => "5.00",
                "total_bet_s" => "225.00",
            ],
            [
                "bet_size" => 50000,
                "bet_multiple" => 10,
                "basic_bet" => 5,
                "total_bet" => 2500000,
                "id" => 30,
                "bet_size_s" => "5.00",
                "total_bet_s" => "250.00",
            ],
            [
                "bet_size" => 200000,
                "bet_multiple" => 1,
                "basic_bet" => 5,
                "total_bet" => 1000000,
                "id" => 31,
                "bet_size_s" => "20.00",
                "total_bet_s" => "100.00",
            ],
            [
                "bet_size" => 200000,
                "bet_multiple" => 2,
                "basic_bet" => 5,
                "total_bet" => 2000000,
                "id" => 32,
                "bet_size_s" => "20.00",
                "total_bet_s" => "200.00",
            ],
            [
                "bet_size" => 200000,
                "bet_multiple" => 3,
                "basic_bet" => 5,
                "total_bet" => 3000000,
                "id" => 33,
                "bet_size_s" => "20.00",
                "total_bet_s" => "300.00",
            ],
            [
                "bet_size" => 200000,
                "bet_multiple" => 4,
                "basic_bet" => 5,
                "total_bet" => 4000000,
                "id" => 34,
                "bet_size_s" => "20.00",
                "total_bet_s" => "400.00",
            ],
            [
                "bet_size" => 200000,
                "bet_multiple" => 5,
                "basic_bet" => 5,
                "total_bet" => 5000000,
                "id" => 35,
                "bet_size_s" => "20.00",
                "total_bet_s" => "500.00",
            ],
            [
                "bet_size" => 200000,
                "bet_multiple" => 6,
                "basic_bet" => 5,
                "total_bet" => 6000000,
                "id" => 36,
                "bet_size_s" => "20.00",
                "total_bet_s" => "600.00",
            ],
            [
                "bet_size" => 200000,
                "bet_multiple" => 7,
                "basic_bet" => 5,
                "total_bet" => 7000000,
                "id" => 37,
                "bet_size_s" => "20.00",
                "total_bet_s" => "700.00",
            ],
            [
                "bet_size" => 200000,
                "bet_multiple" => 8,
                "basic_bet" => 5,
                "total_bet" => 8000000,
                "id" => 38,
                "bet_size_s" => "20.00",
                "total_bet_s" => "800.00",
            ],
            [
                "bet_size" => 200000,
                "bet_multiple" => 9,
                "basic_bet" => 5,
                "total_bet" => 9000000,
                "id" => 39,
                "bet_size_s" => "20.00",
                "total_bet_s" => "900.00",
            ],
            [
                "bet_size" => 200000,
                "bet_multiple" => 10,
                "basic_bet" => 5,
                "total_bet" => 10000000,
                "id" => 40,
                "bet_size_s" => "20.00",
                "total_bet_s" => "1000.00",
            ],
        ];

        foreach ($data as $item) {
            DB::table("tiger_bet_list")->insert($item);
        }
    }
}
